title:                Site
pages:                default
files:                true
fields:
    title:
      label:          Title
      type:           text
      width:          1/2
    author:
      label:          Author
      type:           text
      width:          1/2
      icon:           user-circle-o
    logo:
      label:          Logo
      type:           image
      width:          1/3
    logoinverse:
      label:          Logo Inverse
      type:           image
      width:          1/3
    favicon:
      label:          favicon
      type:           image
      width:          1/3
    copyright:
      label:          Copyright
      type:           text
      width:          1/3
      icon:           copyright
    email:
      label:          Email
      type:           email
      width:          1/3
    bgcolor:
      label:          Primary Color
      type:           color
      width:          1/3
    description:
      label:          Description
      type:           markdown
    tags:
      label:          Tags
      type:           tags
    menu_btn:
      label:          Menu Buttons
      type:           snippetfield
      style:          table
      fields:
        title:
          label:      Title
          type:       text
        url:
          label:      URL
          type:       text
        design:
          label:      Design
          type:       select
          default:    primary
          options:
            primary:  primary
            outlined: outlined
    line:
      type:           line
    facebook:
      label:          facebook
      type:           url
      width:          1/3
      icon:           facebook
    twitter:
      label:          twitter
      type:           url
      width:          1/3
      icon:           twitter
    instagram:
      label:          instagram
      type:           url
      width:          1/3
      icon:           instagram
